import streamlit as st
import lingam
import matplotlib.pyplot as plt
import networkx as nx
from streamlit_sortables import sort_items

def train_causal_model(X):
    causal_model = lingam.DirectLiNGAM()
    causal_model.fit(X)
    return causal_model

def generate_adjacency(graph, fig, ax):
    pos = nx.spring_layout(graph, k=15)
    nx.draw(graph, pos, with_labels=True, node_color='lightblue', edge_color='gray', node_size=2000, font_size=10)
    # Display edge weights
    edge_labels = {(u, v): f"{d['weight']:.2f}" for u, v, d in graph.edges(data=True)}
    nx.draw_networkx_edge_labels(graph, pos, edge_labels=edge_labels, ax=ax)
    st.pyplot(fig)

def edit_adjacency_order(casual_order):
    feature_names = st.session_state.selected_X.columns
    ordered_features = list(map(lambda x: feature_names[x], casual_order))
    sort_items(ordered_features, direction="vertical", key="casual_order_features")
    st.write("Ordered names:", st.session_state.casual_order_features)


if 'classifier_instance' not in st.session_state or 'selected_X' not in st.session_state:
    st.warning("⚠️ Start by initializing classifier in 'Classifier selection'")
else:
    if st.session_state.selected_X is None:
        raise ValueError("selected_X must be initialized in session state")

    # Title
    st.title("Feature Relationship (generated by DirectLiNGAM)")
    st.text("see more about the method: https://pypi.org/project/lingam/")
    casual_model = train_causal_model(st.session_state.selected_X)

    adjacency_matrix = casual_model.adjacency_matrix_
    st.subheader("Edit Adjacency Matrix")
    edited_matrix = st.data_editor(adjacency_matrix, num_rows="dynamic")

    if st.button("🔄 Generate adjacency graph"):
        fig, ax = plt.subplots()
        G = nx.DiGraph(edited_matrix)
        generate_adjacency(G, fig, ax)

    st.subheader("Edit Casual Order")
    edit_adjacency_order(casual_model.causal_order_)

